name: Feature Request
description: Suggest a new feature or enhancement for Arc
labels:
  - enhancement
  - needs triage
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! For broader discussions or brainstorming, consider using [GitHub Discussions](https://github.com/basekick-labs/arc/discussions) instead.

  - type: textarea
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration with Arc?
      placeholder: |
        Example: I'm always frustrated when querying large datasets because there's no way to cache S3 file reads locally.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: |
        Example: Add an SSD cache layer that caches frequently accessed Parquet files locally, with LRU eviction when the cache is full.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        Example: I tried using a caching proxy in front of S3, but it doesn't understand Parquet file access patterns.
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Use Case Category
      description: What category best describes your use case?
      options:
        - IoT / Industrial
        - Observability / Monitoring
        - Financial / Trading
        - Smart Cities
        - Healthcare / Medical
        - Logistics / Fleet
        - General Time-Series
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, benchmarks, or examples about the feature request.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Identity"

  - type: input
    attributes:
      label: Full Name
      placeholder: "John Doe"
    validations:
      required: true

  - type: input
    attributes:
      label: Affiliation
      description: Your company or organization (helps us understand enterprise needs)
      placeholder: "Acme Corporation"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        If the above is not provided and is not obvious from your GitHub profile, we may close your issue without further review.
        Please refer to the [reasoning behind this rule](https://berthub.eu/articles/posts/anonymous-help/) if you have questions.
