apiVersion: v2
name: arc
description: High-performance time-series database built on DuckDB (Go implementation)
type: application
version: 0.2.0
appVersion: "26.06.2"
keywords:
  - database
  - timeseries
  - observability
  - duckdb
  - analytics
  - go
home: https://github.com/basekick-labs/arc
sources:
  - https://github.com/basekick-labs/arc
maintainers:
  - name: Basekick Labs
    email: contact@basekick.com
