{{- if and (eq (include "arc-enterprise.seaweedfsBundled" .) "true") (not .Values.seaweedfs.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arc-enterprise.seaweedfsSecretName" . }}
  labels:
    {{- include "arc-enterprise.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.seaweedfs.credentials.accessKey | quote }}
  secret-key: {{ .Values.seaweedfs.credentials.secretKey | quote }}
{{- end }}
