{{- $sa := .Values.serviceAccount | default dict -}}
{{- if $sa.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "arc-enterprise.serviceAccountName" . }}
  labels:
    {{- include "arc-enterprise.labels" . | nindent 4 }}
  {{- with $sa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
